name: pokket
description: Yet another personal expense tracker app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.5
  flutter_bloc: ^6.0.6
  path: ^1.7.0
  path_provider: ^1.6.18
  sembast: ^2.4.7+7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
